# ¿Este taller es para mi? {#sec-es-para-mi}

El curso está diseñado como taller para investigadores jóvenes y
estudiantes con conocimientos en análisis de datos interesados en
conocer metodologías de análisis con registros nacionales de salud.

Para ayudar a manejar las expectativas y para enfocar el desarrollo de
los materiales, asumiremos cierta experiencia previa de los
participantes de este taller. Esperamos que hayas estudiado, trabajado o
tengas alguna experienca con:

- Conceptos epidemiológicos básicos como prevalencia, determinantes,
  desenlaces, diseño de cohortes abiertas y cerradas, tiempo de
  seguimiento, censura, medidas de incidencia, medidas de riesgo,
  medidas de asociación, sesgos, confusión.

- Manejo de datos cuantitativos, conceptos básicos de la ciencia de
  datos como formatos *long* y *wide*, fusión de datos deterministica y
  probabilistica.

- Análisis de datos con programas estadísiticos como R.

While we have these assumptions to help focus the content of the
workshop, if you have an interest in the workshop but don't fit any of
the assumptions, *you are still welcome to attend*! We welcome everyone
until capacity has been reached.

In addition to the assumptions above, the workshop also has a fairly
focused scope, which may also help you decide if this workshop is for
you:

- TODO: List of concrete tasks we will do and not do.

