# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.11.0
_src_path: gh:rostools/template-workshop
for_rostools: false
github_repo: curso-registros-esp
github_user: sdca-latam
workshop_type: r
