project:
  type: book
  # TODO: Uncomment if you want to use slides.
  # pre-render:
    # - quarto render slides/*.qmd
  # resources:
  #   - slides/*.html

book:
  title: "Introducción al uso de registros nacionales de salud para investigación"
  # TODO: Add more authors if needed.
  author:
    - name: "Daniel R. Witte"
      affiliation: "Steno Diabetes Center Aarhus"
      orcid: "0000-0002-0769-2922"
  date: last-modified
  repo-url: "https://github.com/sdca-latam/curso-registros-esp"
  # TODO: Fill in the URL
  site-url: ""
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Resumen"
      chapters:
        - resumen/temario.qmd
        - resumen/es-para-ti.qmd
        - resumen/horario.qmd
        - resumen/diseño-aprendizaje.qmd
    - part: "Pre-taller"
      chapters:
        - pre-taller/resumen.qmd
        - pre-taller/instalación-programas-r.qmd
        - pre-taller/instalación-paquetes-r.qmd
        - pre-taller/código-de-conducta.qmd
    - part: "Sesiones"
      chapters:
        - sesiones/introducción.qmd
        - sesiones/sessión.qmd
        - sesiones/conclusión.qmd
  appendices:
    - apendices/para-enseñantes.qmd
    - apendices/referencias.qmd
    - CONTRIBUTING.md
    - LICENSE.md
  page-footer:
    center:
      - text: "Licencia: CC BY 4.0"
        href: LICENSE.md
      - text: "Código de Conducta"
        href: "pre-taller/código-de-conducta.qmd"

format:
  html: default
  typst:
    papersize: a4
    margin:
      x: 2cm
      y: 2cm

metadata-files:
  - _metadata.yml
