---
format: gfm
---

# {{< meta tagline >}}

{{< include /includes/_badges.qmd >}}

## Descripción general

Este repositorio contiene los materiales para el curso taller
"Introducción al uso de registros nacionales de salud para
investigación". La primera edición del curso se llevará a cabo el jueves
10 de septiembre 2026 en Lima, Perú.

Para mayor detalle, vea la [página de
bienvenida](https://sdca-latam.github.io/curso-registros-esp/).

::: callout-tip
Este repositorio de taller fue generado con la plantilla
[`template-workshop`](https://template-workshop.rostools.org/) del
proyecto rostools.
:::

## Cómo contribuir

Si te interesa contribuir al desarrollo de los materiales de este
taller, por favor consulta la [guía de contribuidores](CONTRIBUTING.md).

::: content-hidden
For guidelines on how to be a helper or teacher, check out the [For
teachers](https://guides.rostools.org/instructors) page.
:::

Este proyecto tiene un [Código de conducta](CODE_OF_CONDUCT.md). Si
contribuyes o participas en el proyecto, afirmas adherirte al código.

<!-- TODO: Unhide after having contributors -->

::: content-hidden
### Contribuidores
:::

::: content-hidden
### How to cite the material

Please cite the material as:

> TODO: Update when the workshop is published.

Or as BibTeX:

TODO: Update when the workshop is published.
:::
