---
title: "El potencial de los registros"
format: html
---

En esta sesión repasaremos rápidamente algunas de las definiciones

## Objetivos de aprendizaje

El objetivo de esta sesión es que el estudiante conozca y pueda
explicar:

- Qué son los registros sanitarios poblacionales, con enfoque en
  enfermedades crónicas
- Cómo se construyen y mantienen
- Qué los hace tan valiosos
- Cual es la experiencia de los países nórdicos y de Brasil

Tomando el modelo nórdico como ejemplo discutiremos qué tipo de
preguntas de investigación se vuelven posibles con estos datos que de
otro modo serían muy difíciles. Discutiremos fortalezas, limitaciones y
retos. Cerraremos el bloque contrastando con el contexto
latinoamericano/peruano.

## TODO: Section

::: callout-note
## Reading task: \~4 minutes

TODO: Reading text
:::

## :technologist: Exercise: Title

**Time: \~NUM minutes.**

Text

## :speech_balloon: Discussion activity: Title

**Time: \~Num minutes.**

Text

## :book: Reading task: Title

**Time: \~Num minutes.**

Text

## Summary

- TODO: List of summary items

## Survey

{{< include /includes/_survey.qmd >}}

