# Instalación de los programas {#sec-instalación-programas}

Para poder participar en el taller, es importante que tengas los
siguientes programas instalados en tu computadora. Es posible que ya
hayas instalado algunos de ellos en el pasado. En ese caso por favor
verifica que tengas instalada una versión mas reciente que la indicada
en las instrucciones. Si no tendrás que actualizar las instalaciones.

::: panel-tabset
## Windows

1.  [R](https://cloud.r-project.org/bin/windows/base/): Cualquier
    versión mas reciente que {{< meta versions.r >}}. Si has utilizado R
    anteriormente, puedes verificar tu versión actual dando éste comando
    en la consola: `R.version.string`.

2.  [RStudio](https://www.rstudio.com/products/rstudio/download/#download):
    Cualquier versión mas reciente que {{< meta versions.rstudio >}}. Si
    has instalado RStudio anteriormente, puedes verificar la versión
    actual yendo al menu "Help -\> About RStudio".

3.  [Git](https://git-scm.com/download/win): Escoge el enlace "Click
    here to download". Usaremos Git durante algunas partes del taller.
    Al instalar Git, te pedirá seleccionar un "Text Editor" y aunque no
    usaremos esa funcion en el taller es neceario proporcionar el dato
    para la instalación de Git, así que lo mas fácil es escoger Notepad.

## MacOS

1.  [R](https://cloud.r-project.org/bin/macosx/): Cualquier versión mas
    reciente que {{< meta versions.r >}}. Si has utilizado R
    anteriormente, puedes verificar tu versión actual dando éste comando
    en la consola: `R.version.string`. Si usas
    [Homebrew](https://brew.sh/) (recomendado en general pero), la
    instalación de R is muy fácil. Solo hay que dar el siguente comando
    en el Terminal de tu computadora:

    ``` text
    brew install --cask r
    ```

2.  [RStudio](https://www.rstudio.com/products/rstudio/download/#download):
    Cualquier versión mas reciente que {{< meta versions.rstudio >}}. Si
    has instalado RStudio anteriormente, puedes verificar la versión
    actual yendo al menu "Help -\> About RStudio". Con Homebrew:

    ``` text
    brew install --cask rstudio
    ```

3.  [Git](https://git-scm.com/download/mac): Usaremos Git durante
    algunas partes del taller. MacOS viene con Git pre-instalado. Para
    instalarlo con Homebrew:

    ``` text
    brew install git
    ```

## Linux (Ubuntu)

1.  [R](https://cloud.r-project.org/bin/linux/ubuntu/): Cualquier
    versión mas reciente que {{< meta versions.r >}}. Si has utilizado R
    anteriormente, puedes verificar tu versión actual dando éste comando
    en la consola: `R.version.string`.

    ``` text
    sudo apt -y install r-base
    ```

2.  [RStudio](https://www.rstudio.com/products/rstudio/download/#download):
    Cualquier versión mas reciente que {{< meta versions.rstudio >}}. Si
    has instalado RStudio anteriormente, puedes verificar la versión
    actual yendo al menu "Help -\> About RStudio".

3.  [Git](https://git-scm.com/download/mac): Usaremos Git durante
    algunas partes del taller.

    ``` text
    sudo apt install git
    ```
:::

Todos estos programas son necesarios para el taller, Git incluido. Git
es usado para la gestión formal de versiones de archivos. Lo usamos
porque tiene mucha documentación muy buena. Puedes aprender mas en éste
libro en línea [Happy Git with R](https://happygitwithr.com/).
Especialmente la sección "Why Git" explica bien por qué lo usamos.
Usuarios de Windows a veces encuentran dificultades durante la
instalación de Git. La siguiente guia ofrece pautas y ayuda [Installing
Git for
Windows](https://happygitwithr.com/install-git.html#install-git-windows).
