# Tareas preparatorias antes del taller {#sec-pre-workshop}

Para agilizar el taller es importante que todos los participantes
completen las siguientes tareas preparatórias:

::: content-hidden
If you haven't already, go through the workshop overview section,
including the [Syllabus](/overview/syllabus.qmd), [Is this for
you?](/overview/is-this-for-you.qmd), and [Learning
design](/overview/learning-design.qmd) to get an overview of what this
workshop contains and the learning design behind the workshop material.

After that, please go through the the pre-workshop tasks designed to
establish a shared foundation for the start of the workshop. This
includes:
:::

1.  Instala los programas R, RStudio, Quarto, y Git en sus versiones mas
    actuales de acuerdo con @sec-installing-programs.
2.  Instala los paquetes R necesarios.
3.  Lee el temario (@sec-temario).
4.  Lee el [Código de Conducta](/pre-taller/código-de-conducta.qmd)
    (@sec-código-de-conducta).

Cada sección contiene detalles sobre cómo completar cada tarea.

::: callout-tip
Puedes pasar a la siguiente sección haciendo click en la flechita en la
parte inferior de cada página ➡️:
:::
